# Generated by Django 2.0.10 on 2019-02-13 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_announcement_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commen',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='courses.Course', verbose_name='Curso'),
        ),
    ]
